# Analysis of two games
I played against 1000 node V-mode net5000

In [7]:
import os
os.chdir('../src')
import numpy as np
import matplotlib.pyplot as plt
import torch
from tqdm import tqdm
from engine import BigBoard
from network import UTTTNet
from tree import Root
from net_player import NetTree

In [2]:
def load_model(name):
    m = UTTTNet()
    m.load_state_dict(torch.load(f'../models/{name}.pt', map_location='cpu'))
    return m.eval()

In [3]:
game1 = [(4, 4), (4, 0), (0, 8), (8, 8), (8, 0), (0, 0), (0, 7), (7, 7), (7, 2), (2, 2), (2, 6), (6, 6), (6, 2), (2, 5), (5, 0), (0, 1), (1, 1), (1, 3), (3, 1), (1, 6), (6, 1), (1, 0), (0, 6), (6, 3), (3, 3), (3, 5), (5, 3), (3, 7), (7, 3), (3, 8), (8, 7), (7, 8), (8, 4), (4, 6), (6, 0), (4, 3), (3, 2), (2, 8), (8, 5), (5, 8), (8, 3), (3, 6), (7, 6), (5, 5), (5, 6), (7, 0), (7, 4)]
game2 = [(4, 4), (4, 0), (0, 0), (0, 8), (8, 8), (8, 1), (1, 1), (1, 3), (3, 3), (3, 7), (7, 7), (7, 3), (3, 6), (6, 7), (7, 6), (6, 1), (1, 0), (0, 3), (3, 0), (0, 5), (5, 5), (5, 7), (7, 8), (8, 2), (2, 2), (2, 5), (5, 8), (8, 0), (0, 4), (4, 6), (6, 6), (6, 4), (4, 3), (0, 2), (2, 1), (1, 2), (2, 0), (4, 1), (1, 5), (5, 1), (1, 4), (4, 2)]
print(len(game1), len(game2))

47 42


In [4]:
m = load_model('500_5000bs2048lr0.1d0.001e4')

In [10]:
def analyze(game, n, bar=False):
    b = BigBoard()
    for move in game[:-n]:
        b.move(*move)
    b.draw()

    r = Root()
    t = NetTree(b, r, model=m, noise=False)
    for _ in tqdm(range(50000), disable=not bar):
        t.explore()
        if r.terminal[0]:
            break
    print(f'Took {t.N.sum() - len(t.N)} nodes')
    print(t.Q_over_N())

# Game 1

In [18]:
analyze(game1, 1)

     O │ O │   ┃ O │ X │   ┃   │   │ O 
    ───┼───┼───╋───┼───┼───╋───┼───┼───
       │   │   ┃ O │   │   ┃   │   │ O 
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     X │ X │ X ┃ O │   │   ┃ X │   │ O 
    ━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━
       │ X │ X ┃ O │   │   ┃ X │   │   
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     X │   │ O ┃ O │ X │   ┃ X │   │ O 
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     O │ O │ O ┃ O │   │   ┃ X │   │ O 
    ━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━
     X │ X │ X ┃ O │   │ X ┃ X │   │   
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     O │   │   ┃ X │   │   ┃ X │ X │ X 
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     O │   │   ┃ X │ O │ O ┃   │ X │ O         
Mover: X, sector: (0, 1, 2, 3, 4, 5, 6, 7, 8)
     X │ O │ O 
    ───┼───┼───
     O │ O │ X 
    ───┼───┼───
     X │   │ X     
Took 2 nodes
[-0.42600688  1.         -0.20414273]


In [19]:
analyze(game1, 2)

     O │ O │   ┃ O │ X │   ┃   │   │ O 
    ───┼───┼───╋───┼───┼───╋───┼───┼───
       │   │   ┃ O │   │   ┃   │   │ O 
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     X │ X │ X ┃ O │   │   ┃ X │   │ O 
    ━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━
       │ X │ X ┃ O │   │   ┃ X │   │   
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     X │   │ O ┃ O │ X │   ┃ X │   │ O 
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     O │ O │ O ┃ O │   │   ┃ X │   │ O 
    ━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━
     X │ X │ X ┃   │   │ X ┃ X │   │   
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     O │   │   ┃ X │   │   ┃ X │ X │ X 
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     O │   │   ┃ X │ O │ O ┃   │ X │ O         
Mover: O, sector: (0, 1, 2, 3, 4, 5, 6, 7, 8)
     X │ O │ O 
    ───┼───┼───
     O │ O │ X 
    ───┼───┼───
     X │   │ X     
Took 9 nodes
[1. 1. 1. 1.]


In [20]:
analyze(game1, 3)

     O │ O │   ┃ O │ X │   ┃   │   │ O 
    ───┼───┼───╋───┼───┼───╋───┼───┼───
       │   │   ┃ O │   │   ┃   │   │ O 
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     X │ X │ X ┃ O │   │   ┃ X │   │ O 
    ━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━
       │ X │ X ┃ O │   │   ┃ X │   │   
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     X │   │ O ┃ O │ X │   ┃ X │   │ O 
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     O │ O │ O ┃ O │   │   ┃   │   │ O 
    ━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━
     X │ X │ X ┃   │   │ X ┃ X │   │   
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     O │   │   ┃ X │   │   ┃ X │ X │ X 
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     O │   │   ┃ X │ O │ O ┃   │ X │ O         
Mover: X, sector: (5,)
     X │ O │ O 
    ───┼───┼───
     O │ O │   
    ───┼───┼───
     X │   │ X     
Took 27 nodes
[-0.54621196 -0.38643658 -0.44542095  1.         -0.58086893]


In [21]:
analyze(game1, 4)

     O │ O │   ┃ O │ X │   ┃   │   │ O 
    ───┼───┼───╋───┼───┼───╋───┼───┼───
       │   │   ┃ O │   │   ┃   │   │ O 
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     X │ X │ X ┃ O │   │   ┃ X │   │ O 
    ━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━
       │ X │ X ┃ O │   │   ┃ X │   │   
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     X │   │ O ┃ O │ X │   ┃ X │   │   
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     O │ O │ O ┃ O │   │   ┃   │   │ O 
    ━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━
     X │ X │ X ┃   │   │ X ┃ X │   │   
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     O │   │   ┃ X │   │   ┃ X │ X │ X 
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     O │   │   ┃ X │ O │ O ┃   │ X │ O         
Mover: O, sector: (0, 1, 2, 3, 4, 5, 6, 7, 8)
     X │ O │ O 
    ───┼───┼───
     O │ O │   
    ───┼───┼───
     X │   │ X     
Took 114 nodes
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [22]:
analyze(game1, 5)

     O │ O │   ┃ O │ X │   ┃   │   │ O 
    ───┼───┼───╋───┼───┼───╋───┼───┼───
       │   │   ┃ O │   │   ┃   │   │ O 
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     X │ X │ X ┃ O │   │   ┃ X │   │ O 
    ━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━
       │ X │ X ┃ O │   │   ┃ X │   │   
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     X │   │ O ┃ O │ X │   ┃ X │   │   
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     O │ O │ O ┃ O │   │   ┃   │   │ O 
    ━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━
     X │ X │ X ┃   │   │ X ┃ X │   │   
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     O │   │   ┃ X │   │   ┃ X │ X │ X 
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     O │   │   ┃   │ O │ O ┃   │ X │ O         
Mover: X, sector: (0, 1, 2, 3, 4, 5, 6, 7, 8)
     X │ O │ O 
    ───┼───┼───
     O │ O │   
    ───┼───┼───
     X │   │ X     
Took 245 nodes
[-0.54992044 -0.5637457  -0.5376544  -0.51189481 -1.         -1.
 -0.56339226 -0.60613722 -1.         -1.          1.        ]


In [23]:
analyze(game1, 6)

     O │ O │   ┃ O │ X │   ┃   │   │ O 
    ───┼───┼───╋───┼───┼───╋───┼───┼───
       │   │   ┃ O │   │   ┃   │   │ O 
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     X │ X │ X ┃ O │   │   ┃ X │   │ O 
    ━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━
       │ X │ X ┃ O │   │   ┃ X │   │   
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     X │   │ O ┃ O │ X │   ┃ X │   │   
    ───┼───┼───╋───┼───┼───╋───┼───┼───
       │ O │ O ┃ O │   │   ┃   │   │ O 
    ━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━
     X │ X │ X ┃   │   │ X ┃ X │   │   
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     O │   │   ┃ X │   │   ┃ X │ X │ X 
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     O │   │   ┃   │ O │ O ┃   │ X │ O         
Mover: O, sector: (3,)
     X │ O │ O 
    ───┼───┼───
       │ O │   
    ───┼───┼───
     X │   │ X     
Took 672 nodes
[1. 1. 1.]


In [24]:
analyze(game1, 7)

     O │ O │   ┃ O │ X │   ┃   │   │ O 
    ───┼───┼───╋───┼───┼───╋───┼───┼───
       │   │   ┃ O │   │   ┃   │   │ O 
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     X │ X │ X ┃ O │   │   ┃ X │   │ O 
    ━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━
       │ X │ X ┃ O │   │   ┃ X │   │   
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     X │   │ O ┃ O │ X │   ┃ X │   │   
    ───┼───┼───╋───┼───┼───╋───┼───┼───
       │ O │ O ┃ O │   │   ┃   │   │ O 
    ━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━
     X │ X │ X ┃   │   │ X ┃ X │   │   
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     O │   │   ┃ X │   │   ┃   │ X │ X 
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     O │   │   ┃   │ O │ O ┃   │ X │ O         
Mover: X, sector: (8,)
     X │ O │ O 
    ───┼───┼───
       │ O │   
    ───┼───┼───
     X │   │       
Took 748 nodes
[-1. -1.  1. -1.]


In [25]:
analyze(game1, 8)

     O │ O │   ┃ O │ X │   ┃   │   │ O 
    ───┼───┼───╋───┼───┼───╋───┼───┼───
       │   │   ┃ O │   │   ┃   │   │ O 
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     X │ X │ X ┃ O │   │   ┃ X │   │ O 
    ━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━
       │ X │ X ┃ O │   │   ┃ X │   │   
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     X │   │ O ┃ O │ X │   ┃ X │   │   
    ───┼───┼───╋───┼───┼───╋───┼───┼───
       │ O │ O ┃ O │   │   ┃   │   │   
    ━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━
     X │ X │ X ┃   │   │ X ┃ X │   │   
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     O │   │   ┃ X │   │   ┃   │ X │ X 
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     O │   │   ┃   │ O │ O ┃   │ X │ O         
Mover: O, sector: (5,)
     X │ O │ O 
    ───┼───┼───
       │ O │   
    ───┼───┼───
     X │   │       
Took 984 nodes
[1. 1. 1. 1. 1. 1. 1.]


In [26]:
analyze(game1, 9)

     O │ O │   ┃ O │ X │   ┃   │   │ O 
    ───┼───┼───╋───┼───┼───╋───┼───┼───
       │   │   ┃ O │   │   ┃   │   │ O 
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     X │ X │ X ┃ O │   │   ┃ X │   │ O 
    ━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━
       │ X │ X ┃ O │   │   ┃ X │   │   
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     X │   │ O ┃ O │ X │   ┃ X │   │   
    ───┼───┼───╋───┼───┼───╋───┼───┼───
       │ O │ O ┃ O │   │   ┃   │   │   
    ━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━
     X │ X │ X ┃   │   │ X ┃ X │   │   
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     O │   │   ┃ X │   │   ┃   │ X │   
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     O │   │   ┃   │ O │ O ┃   │ X │ O         
Mover: X, sector: (8,)
     X │ O │ O 
    ───┼───┼───
       │ O │   
    ───┼───┼───
     X │   │       
Took 1229 nodes
[-1.         -1.         -0.34399006  1.         -1.        ]


In [27]:
analyze(game1, 10)

     O │ O │   ┃ O │ X │   ┃   │   │ O 
    ───┼───┼───╋───┼───┼───╋───┼───┼───
       │   │   ┃ O │   │   ┃   │   │ O 
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     X │ X │ X ┃ O │   │   ┃ X │   │   
    ━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━
       │ X │ X ┃ O │   │   ┃ X │   │   
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     X │   │ O ┃ O │ X │   ┃ X │   │   
    ───┼───┼───╋───┼───┼───╋───┼───┼───
       │ O │ O ┃ O │   │   ┃   │   │   
    ━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━
     X │ X │ X ┃   │   │ X ┃ X │   │   
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     O │   │   ┃ X │   │   ┃   │ X │   
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     O │   │   ┃   │ O │ O ┃   │ X │ O         
Mover: O, sector: (2,)
     X │ O │   
    ───┼───┼───
       │ O │   
    ───┼───┼───
     X │   │       
Took 9055 nodes
[1. 1. 1. 1. 1. 1.]


Game was already lost 10 moves before, but takes a long search to find all lines.

# Game 2

In [29]:
analyze(game2, 2)

     X │   │ O ┃ X │ X │ O ┃ X │ X │ X 
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     O │ X │ O ┃ O │   │ X ┃   │   │ O 
    ───┼───┼───╋───┼───┼───╋───┼───┼───
       │   │ O ┃   │   │   ┃   │   │   
    ━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━
     X │   │   ┃ O │ O │   ┃   │ O │   
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     X │   │   ┃ X │ X │   ┃   │   │ X 
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     X │ O │   ┃ O │   │   ┃   │ O │ X 
    ━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━
       │ O │   ┃   │   │   ┃ O │ O │ O 
    ───┼───┼───╋───┼───┼───╋───┼───┼───
       │ O │   ┃ O │   │   ┃   │   │   
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     X │ O │   ┃ X │ X │ X ┃   │   │ X         
Mover: X, sector: (1,)
     O │   │ X 
    ───┼───┼───
     X │   │   
    ───┼───┼───
     O │ X │ O     
Took 14 nodes
[-1. -1. -1. -1.]


In [31]:
analyze(game2, 4)

     X │   │ O ┃ X │ X │ O ┃ X │ X │ X 
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     O │ X │ O ┃ O │   │   ┃   │   │ O 
    ───┼───┼───╋───┼───┼───╋───┼───┼───
       │   │ O ┃   │   │   ┃   │   │   
    ━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━
     X │   │   ┃ O │ O │   ┃   │   │   
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     X │   │   ┃ X │ X │   ┃   │   │ X 
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     X │ O │   ┃ O │   │   ┃   │ O │ X 
    ━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━
       │ O │   ┃   │   │   ┃ O │ O │ O 
    ───┼───┼───╋───┼───┼───╋───┼───┼───
       │ O │   ┃ O │   │   ┃   │   │   
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     X │ O │   ┃ X │ X │ X ┃   │   │ X         
Mover: X, sector: (1,)
     O │   │ X 
    ───┼───┼───
     X │   │   
    ───┼───┼───
     O │ X │ O     
Took 68 nodes
[-1. -1. -1. -1. -1.]


In [11]:
analyze(game2, 6)

     X │   │ O ┃ X │ X │ O ┃   │ X │ X 
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     O │ X │ O ┃ O │   │   ┃   │   │ O 
    ───┼───┼───╋───┼───┼───╋───┼───┼───
       │   │ O ┃   │   │   ┃   │   │   
    ━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━
     X │   │   ┃ O │   │   ┃   │   │   
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     X │   │   ┃ X │ X │   ┃   │   │ X 
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     X │ O │   ┃ O │   │   ┃   │ O │ X 
    ━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━
       │ O │   ┃   │   │   ┃ O │ O │ O 
    ───┼───┼───╋───┼───┼───╋───┼───┼───
       │ O │   ┃ O │   │   ┃   │   │   
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     X │ O │   ┃ X │ X │ X ┃   │   │ X         
Mover: X, sector: (2,)
     O │   │   
    ───┼───┼───
     X │   │   
    ───┼───┼───
     O │ X │ O     
Took 788 nodes
[-1. -1. -1. -1. -1. -1.]


In [12]:
analyze(game2, 8, bar=True)

  0%|          | 28/50000 [00:00<03:03, 272.98it/s]

     X │   │ O ┃ X │ X │   ┃   │   │ X 
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     O │ X │ O ┃ O │   │   ┃   │   │ O 
    ───┼───┼───╋───┼───┼───╋───┼───┼───
       │   │ O ┃   │   │   ┃   │   │   
    ━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━
     X │   │   ┃ O │   │   ┃   │   │   
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     X │   │   ┃ X │ X │   ┃   │   │ X 
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     X │ O │   ┃ O │   │   ┃   │ O │ X 
    ━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━
       │ O │   ┃   │   │   ┃ O │ O │ O 
    ───┼───┼───╋───┼───┼───╋───┼───┼───
       │ O │   ┃ O │   │   ┃   │   │   
    ───┼───┼───╋───┼───┼───╋───┼───┼───
     X │ O │   ┃ X │ X │ X ┃   │   │ X         
Mover: X, sector: (2,)
     O │   │   
    ───┼───┼───
     X │   │   
    ───┼───┼───
     O │ X │ O     


100%|██████████| 50000/50000 [01:21<00:00, 615.18it/s] 

Took 50000 nodes
[-0.12468145 -1.         -0.69318798 -1.         -0.70159017 -1.
 -0.68993083]


Maxed out nodes. Search suggests that (2,0) is not losing:
- After (2,0) if (4,1) (1,2)! (2,o) (4,5) X wins.
- After (2,0) if (1,2) (2,1)! (1,5) (5,1) (1,o) (4,5) (5,2) (5,4) X is winning on (5,0) and (5,3)
    - After (2,1) if (1,4) (4,5) (5,1) (1,x) (5,4) sector 1 will be drawn and game is drawn?
- After (2,0) (4,2) (2,1)! (1,2) does not send X to sector 2 because 2 is already won by X.
    - After (2,1) if (1,2) (4,5)! (5,2) (1,4) (1,5) (5,4) (1,8) (5,3) X wins.
        - After (4,5) if (5,1) (1,4) X is also winning.
        - I think O cannot play (1,2) after (2,1) because of (4,5)! X gains too many win threats after winning the center sector.
    - After (2,1) if (1,5) what next?

#### From batch analysis

In [ ]:
np.set_printoptions(suppress=True)
while True:
    metric = t.sign * t.Q / t.N
    index = np.argmax(metric)
    print('-----')
    print(np.stack([t.N, t.Q_over_N()]).T)
    t = t.goto(index)

```
[[47392.     -0.1307422 ]
 [ 1234.     -1.        ]
 [  267.     -0.69468112]
 [  261.     -1.        ]
 [  240.     -0.702226  ]
 [  347.     -1.        ]
 [  266.     -0.69159733]]
-----
[[ 4453.     -0.19657368]
 [  479.     -0.15091288]
 [  145.      1.        ]
 [   88.      1.        ]
 [  108.      1.        ]
 [ 1243.      1.        ]
 [   58.      1.        ]
 [   97.      1.        ]
 [  497.     -0.15973671]
 [   77.      1.        ]
 [   79.      1.        ]
 [   56.      1.        ]
 [   75.      1.        ]
 [  852.      1.        ]
 [22898.     -0.2004676 ]
 [   73.      1.        ]
 [   64.      1.        ]
 [  265.      1.        ]
 [   79.      1.        ]
 [14778.     -0.19838524]
 [   73.      1.        ]
 [  598.     -0.15262735]
 [  278.      1.        ]]
-----
[[   26.     -0.69736693]
 [  202.     -0.64911976]
 [22450.     -0.17654471]
 [   82.     -0.68082363]
 [  110.     -0.68315173]
 [   32.     -0.71866542]]
-----
[[20863.     -0.30378106]
 [  438.      1.        ]
 [  130.      1.        ]
 [  229.      1.        ]
 [  524.      1.        ]
 [  270.      1.        ]]
-----
[[20592.     -0.22273239]
 [   68.     -1.        ]
 [   46.     -1.        ]
 [   77.     -1.        ]
 [   41.     -1.        ]
 [   43.     -1.        ]]
-----
[[4324.    -0.13591502]
 [4086.    -0.12909999]
 [5971.    -0.14652216]
 [3060.    -0.13281612]
 [3154.    -0.14142291]]
-----
[[  28.    -1.        ]
 [  31.    -1.        ]
 [  26.    -1.        ]
 [  25.    -1.        ]
 [  42.    -1.        ]
 [5769.    -0.03670075]
 [  27.    -1.        ]
 [  29.    -1.        ]]
-----
[[2961.    -0.03565076]
 [1290.    -0.00884263]
 [ 243.     0.0762014 ]
 [1277.    -0.03189646]]
-----
[[  65.    -0.3299187 ]
 [  47.    -0.32034202]
 [  90.    -0.20726371]
 [ 739.     0.        ]
 [1979.     0.        ]
 [  45.    -0.2117094 ]]
-----
[[ 3.  1.]
 [ 3.  1.]
 [ 3.  1.]
 [21.  0.]
 [ 3.  1.]]
-----
[[ 3. -1.]
 [ 5. -1.]
 [ 5. -1.]
 [10.  0.]]
```

In [ ]:
# Principal Variation from 50k analysis. Both end in draws.
PV_V = [[2, 0], [4, 5], [5, 2], [2, 1], [1, 2], [2, 6], [4, 2], [2, 3], [4, 1], [4, 7], [4, 8]]
PV_N = [[2, 0], [4, 5], [5, 2], [2, 1], [1, 2], [2, 6], [4, 2], [2, 3], [4, 7], [4, 1], [2, 4], [4, 8]]